version: '3'
services:

  mongodb:
    image: mongo
    hostname: ${MONGODB_CONTAINER_NAME}
    container_name: ${MONGODB_CONTAINER_NAME}
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - /zestic/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - zestic.internal
      - zestic.external
      - overnet

networks:
  zestic.internal:
    external: true
  zestic.external:
    external: true
  overnet:
    external: true
    driver: overlay
