version: '3'
services:
  nginx_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "nginx_mysql"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "nginx"
      DB_MYSQL_PASSWORD: "nginxrw"
      DB_MYSQL_NAME: "nginx"
    volumes:
      - ./data/nginx:/data
      - ./data/letsencrypt:/etc/letsencrypt
    networks:
      - nginx-network

  nginx_mysql:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/mariadb.conf.d/my.cnf:ro
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MARIADB
      MYSQL_USER: nginx
      MYSQL_PASSWORD: nginxrw
      MYSQL_DATABASE: nginx
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge