---
version: '3.6'
services:
        mysql:
                image: mysql:5.7
                hostname: mysql
                container_name: mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: wordpress
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: wordpress
                        MYSQL_PASSWORD: wordpress
                volumes:
                        - $HOME/data/wordpress/mysql:/var/lib/mysql
                ports:
                        - "3306:3306"

        wordpress:
                depends_on:
                        - mysql
                image: wordpress:latest
                volumes:
                        - $HOME/data/wordpress/data:/var/www/html
                ports:
                        - "8000:80"
                restart:
                        always
                environment:
                        WORDPRESS_DB_HOST: mysql:3306
                        WORDPRESS_DB_USER: wordpress
                        WORDPRESS_DB_PASSWORD: wordpress
                        WORDPRESS_DB_NAME: wordpress
networks:
        default:
                external:
                        name: nginx-proxy                
                  
