version: "3.6"
#all port number should be exposed appending 9
services:

  nginx:
    image: 'zesticio/nginx:latest'
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ${DATA}/nginx/config:/etc/nginx
      - ${DATA}/nginx/html:/var/www/html
    networks:
      - portainer

networks:
  portainer:
    name: portainer
    external: true