version: '3.6'

services:        
        jenkins:
                image: jenkins/jenkins:latest
                privileged: true
                user: root
                container_name: jenkins
                restart: unless-stopped
                networks:
                        - jenkins-network
                ports:
                        - "6080:8080"
                        - "50000:50000"
                volumes:
                        - $HOME/data/jenkins:/var/jenkins_home
                        - ~/var/run/docker.sock:/var/run/docker.sock
networks:
        jenkins-network:
                name: jenkins-network
                driver: bridge
