version: "3.6"

services:
        discovery:
                build:
                        context: .
                        dockerfile: Dockerfile
                hostname: discovery
                container_name: discovery
                ports:
                        - 8761:8761
                volumes:
                        - $HOME/data/discovery:/data
                environment:
                        - "JAVA_OPTS=-XX:MaxRAM=256m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
                        - "TZ=Asia/Calcutta"
                        - "SPRING_PROFILES_ACTIVE=dev"
                restart: always
                networks:
                        - authy.network

networks:
        authy.network:
                external: true
                name: authy.network
