version: '2'
services:
  portainer:
    container_name: portainer
    image: 'portainer/portainer-ce:latest'
    restart: always
    privileged: true
    ports:
      - '6443:9443'
    volumes:
      - /zestic/data/portainer/data:/data:Z
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - zestic.internal
      - zestic.external
networks:
  zestic.internal:
    external: true
  zestic.external:
    external: true
